import { Icon } from '@mui/material';

export const categories = [
  { name: 'Lake', icon: <Icon>kayaking_outlined_icon</Icon> },
  { name: 'Earth homes', icon: <Icon>search</Icon> },
  { name: 'Iconic cities', icon: <Icon>search</Icon> },
  { name: 'Islands', icon: <Icon>search</Icon> },
  { name: 'National parks', icon: <Icon>search</Icon> },
  { name: 'OMG!', icon: <Icon>search</Icon> },
  { name: 'Surfing', icon: <Icon>search</Icon> },
  { name: 'Tropical', icon: <Icon>search</Icon> },
  { name: 'Camping', icon: <Icon>search</Icon> },
  { name: 'Amazing views', icon: <Icon>search</Icon> },
  { name: 'Castles', icon: <Icon>search</Icon> },
  { name: 'Campers', icon: <Icon>search</Icon> },
  { name: 'Amazing pools', icon: <Icon>search</Icon> },
  { name: 'Arctic', icon: <Icon>search</Icon> },
  { name: 'Design', icon: <Icon>search</Icon> },
  { name: 'Cabins', icon: <Icon>search</Icon> },
  { name: 'Lakefront', icon: <Icon>search</Icon> },
  { name: 'Beach', icon: <Icon>search</Icon> },
  { name: 'Tiny homes', icon: <Icon>search</Icon> },
  { name: 'Caves', icon: <Icon>search</Icon> },
  { name: 'Bed & breakfasts', icon: <Icon>search</Icon> },
  { name: 'New', icon: <Icon>search</Icon> },
  { name: 'Trending', icon: <Icon>search</Icon> },
  { name: 'Golfing', icon: <Icon>search</Icon> },
  { name: 'Rooms', icon: <Icon>search</Icon> },
  { name: 'Mansions', icon: <Icon>search</Icon> },
  { name: 'Historical homes', icon: <Icon>search</Icon> },
  { name: 'Farms', icon: <Icon>search</Icon> },
  { name: 'Countryside', icon: <Icon>search</Icon> },
  { name: 'A-frames', icon: <Icon>search</Icon> },
  { name: 'Top of the world', icon: <Icon>search</Icon> },
  { name: 'Skiing', icon: <Icon>search</Icon> },
  { name: 'Hanoks', icon: <Icon>search</Icon> },
  { name: 'Luxe', icon: <Icon>search</Icon> },
  { name: 'Vineyards', icon: <Icon>search</Icon> },
  { name: 'Cycladic homes', icon: <Icon>search</Icon> },
  { name: 'Windmills', icon: <Icon>search</Icon> },
  { name: "Chef's kitchens", icon: <Icon>search</Icon> },
  { name: 'Beachfront', icon: <Icon>search</Icon> },
  { name: 'Casas particulares', icon: <Icon>search</Icon> },
  { name: 'Treehouses', icon: <Icon>search</Icon> },
  { name: "Shepherd's huts", icon: <Icon>search</Icon> },
  { name: 'Domes', icon: <Icon>search</Icon> },
  { name: 'Ryokans', icon: <Icon>search</Icon> },
  { name: 'Towers', icon: <Icon>search</Icon> },
  { name: 'Minsus', icon: <Icon>search</Icon> },
  { name: 'Barns', icon: <Icon>search</Icon> },
  { name: 'Yurts', icon: <Icon>search</Icon> },
  { name: 'Desert', icon: <Icon>search</Icon> },
  { name: 'Adapted', icon: <Icon>search</Icon> },
  { name: 'Play', icon: <Icon>search</Icon> },
  { name: 'Ski-in/out', icon: <Icon>search</Icon> },
  { name: 'Boats', icon: <Icon>search</Icon> },
  { name: 'Houseboats', icon: <Icon>search</Icon> },
  { name: 'Off-the-grid', icon: <Icon>search</Icon> },
  { name: 'Containers', icon: <Icon>search</Icon> },
  { name: 'Creative spaces', icon: <Icon>search</Icon> },
  { name: 'Grand pianos', icon: <Icon>search</Icon> },
  { name: 'Dammusi', icon: <Icon>search</Icon> },
  { name: 'Riads', icon: <Icon>search</Icon> },
  { name: 'Trulli', icon: <Icon>search</Icon> },
];
